global:
  scrape_interval: 5s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Мониторинг вашего webapp
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'raspberrypi'
    static_configs:
      - targets: ['192.168.1.43:9100']
